# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEVELOPMENT"] %>
  twilio_sid: <%= ENV["TWILIO_SID_TEST"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN_TEST"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  goodle_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  goodle_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  ian_phone: <%= ENV["IAN_PHONE"] %>
  ian_email: <%= ENV["IAN_EMAIL"] %>
  clara_phone: <%= ENV["CLARA_PHONE"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>
  twilio_sid: <%= ENV["TWILIO_SID_TEST"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN_TEST"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  goodle_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  goodle_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  ian_phone: <%= ENV["IAN_PHONE"] %>
  ian_phone: <%= ENV["IAN_EMAIL"] %>
  clara_phone: <%= ENV["CLARA_PHONE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
  goodle_client_id: <%= ENV["GOOGLE_CLIENT_ID"] %>
  goodle_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"] %>
  ian_phone: <%= ENV["IAN_PHONE"] %>
  ian_phone: <%= ENV["IAN_EMAIL"] %>
  clara_phone: <%= ENV["CLARA_PHONE"] %>
